### PR TITLE
Adding the option to skip reviewing a repository.

### PR DESCRIPTION
**Pull request by SunSparc**
I have some repositories in my list that I consistently ignore, for one reason or another, and instead of deleting them or cleaning them up, I thought it would be nice to just skip them, until I want to deal with them. Let me know what you think of this.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
Yeah, this is something I've kind of wanted too.

**Comment by SunSparc** [comment]
Oh good! Then I hope you like my implementation. I like the use of the git config keys.

**Comment by mdwhatcott** [comment]
@SunSparc - Could you include in a comment what the entries in your git config file look like?

**Comment by SunSparc** [comment]
Sure, here is the contents of my config file for a repository:

```
cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[review]
	skip = true
```

**Comment by mdwhatcott** [comment]
Nice! I like it.

**Comment by mdwhatcott** [comment]
Just published `v0.2.0`

**Pull request merged**
